FROM n8nio/n8n:latest

ENV DB_TYPE=sqlite
ENV N8N_PORT=5678
ENV PORT=5678
ENV N8N_LISTEN_ADDRESS=0.0.0.0
ENV GENERIC_TIMEZONE=America/Bogota
ENV TZ=America/Bogota
ENV N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
ENV N8N_RUNNERS_ENABLED=false
ENV NODE_OPTIONS="--max-old-space-size=450"

EXPOSE 5678
