version: '3.8'

networks:
  tictac_net:
    driver: bridge

volumes:
  n8n_storage:
  openwa_storage:
services:
  n8n:
    image: n8nio/n8n:2.32.6@sha256:5f7856f4fc7cd935230f7596e39fdb3d5eda0e379c5b40b699b9c0eb35ebd0bf
    container_name: n8n_tictac
    restart: unless-stopped
    networks:
      - tictac_net
    ports:
      - "5678:5678"
    volumes:
      - n8n_storage:/home/node/.n8n
    environment:
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE:-America/Bogota}
      - TZ=${TZ:-America/Bogota}
      - WEBHOOK_URL=${WEBHOOK_URL}
      
  openwa:
    image: openwa/wa-automate:latest
    container_name: openwa_tictac
    restart: unless-stopped
    networks:
      - tictac_net
    ports:
      - "8080:8080"
    volumes:
      - openwa_storage:/app/session
    environment:
      - WA_CLI_ARGS=--use-chrome --web-api-key=${OPENWA_API_KEY:?OPENWA_API_KEY es obligatoria} --dashboard
