FROM n8nio/n8n:latest

ENV N8N_HOST=0.0.0.0
ENV N8N_LISTEN_ADDRESS=0.0.0.0
ENV N8N_PORT=5678
ENV PORT=5678
ENV N8N_PROTOCOL=https
ENV GENERIC_TIMEZONE=America/Bogota
ENV TZ=America/Bogota
ENV N8N_RUNNERS_ENABLED=false
ENV N8N_PERSONALIZATION_ENABLED=false
ENV N8N_METRICS=false
ENV NODE_OPTIONS="--max-old-space-size=380"

EXPOSE 5678
