services:
  - type: web
    name: n8n-gafas-antioquia
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    region: oregon
    envVars:
      - key: DB_TYPE
        value: sqlite
      - key: N8N_PORT
        value: "5678"
      - key: PORT
        value: "5678"
      - key: N8N_LISTEN_ADDRESS
        value: 0.0.0.0
      - key: GENERIC_TIMEZONE
        value: America/Bogota
      - key: TZ
        value: America/Bogota
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: "true"
      - key: N8N_RUNNERS_ENABLED
        value: "false"
      - key: NODE_OPTIONS
        value: "--max-old-space-size=450"
      - key: N8N_WEBHOOK_URL
        value: https://n8n-gafas-antioquia.onrender.com/
