services:
  - type: web
    name: n8n-gafas-antioquia
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    region: oregon
    envVars:
      - key: DB_TYPE
        value: sqlite
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_LISTEN_ADDRESS
        value: 0.0.0.0
      - key: N8N_PORT
        value: "5678"
      - key: PORT
        value: "5678"
      - key: N8N_PROTOCOL
        value: https
      - key: WEBHOOK_URL
        value: https://n8n-gafas-antioquia.onrender.com/
      - key: N8N_EDITOR_BASE_URL
        value: https://n8n-gafas-antioquia.onrender.com/
      - key: GENERIC_TIMEZONE
        value: America/Bogota
      - key: TZ
        value: America/Bogota
      - key: N8N_RUNNERS_ENABLED
        value: "false"
      - key: N8N_PERSONALIZATION_ENABLED
        value: "false"
      - key: N8N_METRICS
        value: "false"
      - key: NODE_OPTIONS
        value: "--max-old-space-size=380"
